### ISSUE TITLE
update to work with current release

### ISSUE THREAD

**Issue by bsr203** [chunhtai/flutter-nested-router#1]
Hello.

May  be due to the recent changes, currently there are few build errors. I couldn't see any reference of `PlatformRoutePackageProvider` in flutter repository as well. It would be a great reference if you can update to work with current flutter version.

Thanks.
bsr.

few errors:
```
Undefined class 'PlatformRoutePackageProvider'.
Missing concrete implementations of 'Listenable.addListener' and 'Listenable.removeListener'.
Undefined class 'RoutePackage'.

```

**Comment by chunhtai** [comment]
Hi @bsr203 This is an experimental package and I don't have plan to continue on this package. We are currently exploring new ways to simplify route parsing and nested routers, so I would like to abandon this one.

**Comment by bsr203** [comment]
thank you for the prompt response.
